
package net.Myservice_convert_MtoKM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyServ", targetNamespace = "http://myServ")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServ {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertMtoKm")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertMtoKm", targetNamespace = "http://myServ", className = "myserv.ConvertMtoKm")
    @ResponseWrapper(localName = "ConvertMtoKmResponse", targetNamespace = "http://myServ", className = "myserv.ConvertMtoKmResponse")
    public double convertMtoKm(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
