
package net.Myservice_convert_MtoKM;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyServService", targetNamespace = "http://myServ", wsdlLocation = "http://localhost:9090/MyServer/services/MyServPort?wsdl")
public class MyServService
    extends Service
{

    private final static URL MYSERVSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSERVSERVICE_EXCEPTION;
    private final static QName MYSERVSERVICE_QNAME = new QName("http://myServ", "MyServService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/MyServer/services/MyServPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVSERVICE_WSDL_LOCATION = url;
        MYSERVSERVICE_EXCEPTION = e;
    }

    public MyServService() {
        super(__getWsdlLocation(), MYSERVSERVICE_QNAME);
    }

    public MyServService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVSERVICE_QNAME, features);
    }

    public MyServService(URL wsdlLocation) {
        super(wsdlLocation, MYSERVSERVICE_QNAME);
    }

    public MyServService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVSERVICE_QNAME, features);
    }

    public MyServService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyServ
     */
    @WebEndpoint(name = "MyServPort")
    public MyServ getMyServPort() {
        return super.getPort(new QName("http://myServ", "MyServPort"), MyServ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyServ
     */
    @WebEndpoint(name = "MyServPort")
    public MyServ getMyServPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://myServ", "MyServPort"), MyServ.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVSERVICE_EXCEPTION!= null) {
            throw MYSERVSERVICE_EXCEPTION;
        }
        return MYSERVSERVICE_WSDL_LOCATION;
    }

}
